---
- name: ansible playbook to test ansible vault
  hosts: all
  become: true
  tasks:
  - name: clone a repo
    git:
      repo: https://github.com/anandranjan012/vault.git
      dest: /opt/ansadmin/test-vault

