---
- name: this playbook install httpd
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
   
    when: ansible_os_family == "RedHat"
    
  
  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes    

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    

  - name: copy incex.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
#    when: ansible_os_family == "Debian"
